from __future__ import annotations

from typing import Any, Protocol


class PersonaStore(Protocol):
    def list_personas(self) -> list[dict[str, Any]]: ...
    def get_persona(self, persona_id: str) -> dict[str, Any] | None: ...
    def create_persona(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def update_persona(
        self, persona_id: str, payload: dict[str, Any]
    ) -> dict[str, Any] | None: ...
    def delete_persona(self, persona_id: str) -> bool: ...


class SessionStore(Protocol):
    def list_sessions(self) -> list[dict[str, Any]]: ...
    def get_session(self, session_id: str) -> dict[str, Any] | None: ...
    def create_session(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def delete_session(self, session_id: str) -> bool: ...


class ReportStore(Protocol):
    def list_report_ids(self) -> list[str]: ...
    def get_report(self, session_id: str) -> dict[str, Any] | None: ...
    def save_report(self, session_id: str, payload: dict[str, Any]) -> None: ...
    def delete_report(self, session_id: str) -> bool: ...
    def clear_reports(self) -> None: ...


class MetricsStore(Protocol):
    def list_metrics(self) -> list[dict[str, Any]]: ...
    def get_metric(self, session_id: str) -> dict[str, Any] | None: ...
    def save_metric(self, payload: dict[str, Any]) -> None: ...
    def delete_metric(self, session_id: str) -> bool: ...
    def clear_metrics(self) -> None: ...
    def get_aggregate(self) -> dict[str, Any]: ...
    def list_metrics_in_range(
        self, start_iso: str | None, end_iso: str | None
    ) -> list[dict[str, Any]]: ...


class DraftStore(Protocol):
    def create_draft(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def get_latest_draft(self) -> dict[str, Any] | None: ...
    def update_draft(self, draft_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...
    def delete_draft(self, draft_id: str) -> bool: ...


class SessionContextStore(Protocol):
    def set_session_context(
        self, session_id: str, payload: dict[str, Any]
    ) -> dict[str, Any]: ...
    def get_session_context(self, session_id: str) -> dict[str, Any] | None: ...
