# services/gemini/imagen/client.py

import logging
from typing import Optional

from google import genai
from google.genai import types  # type: ignore

logger = logging.getLogger("gemini_imagen")


class ImagenError(Exception):
    """Exception raised when Imagen API fails."""
    pass


class GeminiImagenClient:
    """
    Client for generating persona images using Google's Imagen API.
    
    This client generates professional portrait images based on persona
    descriptions derived from session context data.
    """

    def __init__(self):
        """Initialize the Imagen client."""
        self._client = genai.Client()
        self._model = "imagen-4.0-fast-generate-001"

    async def generate_persona_image(
        self,
        session_context: dict,
    ) -> bytes:
        """
        Generate a persona image based on session context.

        Creates a professional portrait image that represents the AI persona
        based on demographic and role information from the session context.

        Args:
            session_context: Dictionary containing session configuration including
                prospect identity fields (job_title, industry, company_name, etc.)

        Returns:
            Image data as bytes (PNG format)

        Raises:
            ImagenError: If image generation fails or returns no results
        """
        try:
            # Build the image generation prompt from session context
            prompt = self._build_prompt_from_context(session_context)
            
            logger.info(f"Generating persona image with prompt: {prompt}")

            # Generate the image using Imagen API
            response = self._client.models.generate_images(
                model=self._model,
                prompt=prompt,
                config=types.GenerateImagesConfig(
                    number_of_images=1,
                    aspect_ratio="1:1",  # Square format for participant tiles
                    person_generation="allow_adult",  # Allow adult portraits
                ),
            )

            if not response.generated_images:
                raise ImagenError("No images generated by Imagen API")

            # Get the first generated image
            generated_image = response.generated_images[0]
            image_bytes = generated_image.image.image_bytes

            logger.info("Successfully generated persona image")
            return image_bytes

        except Exception as exc:
            error_msg = f"Failed to generate persona image: {str(exc)}"
            logger.error(error_msg)
            raise ImagenError(error_msg) from exc

    def _build_prompt_from_context(self, session_context: dict) -> str:
        """
        Build an Imagen prompt from session context.

        Creates a descriptive prompt for generating a professional portrait
        that matches the persona's role, industry, and demographic details.

        Args:
            session_context: Session configuration dictionary

        Returns:
            Prompt string for Imagen API
        """
        # Extract relevant fields from session context
        job_title = session_context.get("job_title", "professional")
        industry = session_context.get("industry", "business")
        department = session_context.get("department", "")
        company_size = session_context.get("company_size", "")
        prospect_name = session_context.get("prospect_name", "")

        # Build a detailed prompt for a professional portrait
        # Focus on professional appearance, business setting
        parts = [
            "A professional headshot portrait of a",
        ]

        # Add job title context
        if job_title:
            parts.append(f"{job_title.lower()}")

        # Add industry/department context
        if department:
            parts.append(f"in {department.lower()}")
        elif industry:
            parts.append(f"in {industry.lower()}")

        # Add style and quality modifiers
        parts.extend([
            ", business professional,",
            "confident and approachable,",
            "professional office background,",
            "soft natural lighting,",
            "modern corporate photography style,",
            "high quality,",
            "professional headshot,",
            "LinkedIn profile style"
        ])

        prompt = " ".join(parts)
        
        return prompt
